### ISSUE TITLE
[Bug] Google's deprecation in Protobuf message to json causes dbt operations to fail

### ISSUE THREAD

**Issue by nlawrencenerd13** [dbt-labs/dbt-common#94] opened 2024-03-13 20:32 UTC
### Is this a new bug in dbt-common?

- [X] I believe this is a new bug in dbt-common
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

DBT should be able to compile, however, since google has removed a keyword argument from this change: https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf
The provided keyword argument for 
``` def to_json(self):
         return MessageToJson(
             self.pb_msg, preserving_proto_field_name=True, including_default_valud_fields=True
          )
```
include_default_valud_fields (It might be a typo on my machine?) fails and will not compile

### Expected Behavior

DBT should be able to compile the project. 

### Steps To Reproduce

1. dbt-core 1.7.9
2. dbt-snowflake 1.7.* (I think the issue is in dbt-core though in this library)
3. run dbt compile on a project
4. Returns error TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/dbt", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/main.py", line 155, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/requires.py", line 109, in wrapper
    fire_event(
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/events/functions.py", line 270, in fire_event
    EVENT_MANAGER.fire_event(e, level=level)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/events/eventmgr.py", line 17, in fire_event
    msg = msg_from_base_event(e, level=level)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/events/base_types.py", line 143, in msg_from_base_event
    "msg": event.message(),
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/events/types.py", line 2414, in message
    return f"Resource report: {self.to_json()}"
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/events/base_types.py", line 104, in to_json
    return MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
```

### Additional Context

Google python protobuf change: https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf

**Comment by dbeatty10** [comment] 2024-03-13 23:10
Thanks for reporting this @nlawrencenerd13 !

This looks the same as https://github.com/dbt-labs/dbt-core/issues/9759, so I'm going to close this as a duplicate of that one.

In the meantime, at least one user reported that the following can be used as a fix:

```shell
python -m pip install protobuf==4.25.3
```

**Closed by dbeatty10** 2024-03-13 23:10 UTC
Labels: bug, triage
